[env]
PROJECT_NAME = "FastAPI MongoDB Vue Stack Demo"
DOMAIN = "localhost"
STACK_NAME = "fmv-demo"

DOCKER_IMAGE_BACKEND = "ghcr.io/lambchop4prez/fmv-demo-backend"
DOCKER_IMAGE_FRONTEND = "ghcr.io/lambchop4prez/fmv-demo-frontend"
BACKEND_REPOSITORY = "mongodb"
# BACKEND_REPOSITORY=inmemory
BACKEND_MONGO_HOST = "localhost"
BACKEND_MONGO_DATABASE = "robot"
BACKEND_BROKER_HOST = "localhost"

FRONTEND_API_BASE_URL = "http://localhost:8000"

_.file = ["{{config_root}}/.secrets.env"]

[tools]
"python" = "3.14.3"
"aqua:astral-sh/uv" = "0.10.4"
"aqua:casey/just" = "1.46.0"
"aqua:charmbracelet/gum" = "0.17.0"
"aqua:jqlang/jq" = "1.8.1"
"aqua:rhysd/actionlint" = "1.7.11"
"aqua:pnpm/pnpm" = "10.30.1"
"npm:cspell" = "9.6.4"
"pipx:python-semantic-release" = "10.5.3"
