[env]
PROJECT_NAME = "FastAPI MongoDB Vue Stack Demo"
DOMAIN = "localhost"
STACK_NAME = "fmv-demo"

DOCKER_IMAGE_BACKEND = "ghcr.io/lambchop4prez/fmv-demo-backend"
DOCKER_IMAGE_FRONTEND = "ghcr.io/lambchop4prez/fmv-demo-frontend"
TAG = "0.0.0-dirty"

BACKEND_REPOSITORY = "mongodb"
# BACKEND_REPOSITORY=inmemory
BACKEND_MONGO_HOST = "localhost"
BACKEND_MONGO_DATABASE = "robot"
BACKEND_BROKER_HOST = "localhost"

FRONTEND_API_BASE_URL = "http://localhost:8000"

_.file = ["{{config_root}}/.secrets.env"]

[tools]
"python" = "3.14.2"
"aqua:astral-sh/uv" = "0.9.28"
"aqua:casey/just" = "1.46.0"
"aqua:charmbracelet/gum" = "0.17.0"
"aqua:jqlang/jq" = "1.8.1"
"aqua:rhysd/actionlint" = "1.7.10"
"aqua:pnpm/pnpm" = "10.28.2"
"npm:cspell" = "9.6.3"
"pipx:python-semantic-release" = "10.5.3"
